from . import test_oski_module
from . import test_download_controller
from . import test_version_selector
from . import test_facets
from . import test_url_state
from . import test_odoo_version_registry
from . import test_screenshots
from . import test_module_page
from . import test_build_zip
from . import test_purchase_entitlement
from . import test_version_order_and_legal
from . import test_buy_route
from . import test_i18n_source
from . import test_bilingual_render
from . import test_counters
