from . import test_oski_module
from . import test_download_controller
from . import test_version_selector
from . import test_facets
from . import test_url_state
from . import test_odoo_version_registry
from . import test_screenshots
from . import test_module_page
from . import test_build_zip
