{
    "name": "Assistance (Helpdesk) — Oski",
    "version": "19.0.1.0.0",
    "category": "Services/Helpdesk",
    "summary": "Gérez les demandes client sans en perdre une seule : tickets numérotés, alias email, assignation équilibrée, kanban par étape.",
    "author": "OdooSkills",
    "website": "https://apps.odooskills.com",
    "support": "support@odooskills.com",
    "license": "LGPL-3",
    "depends": ["base", "mail"],
    "data": [
        "security/helpdesk_security.xml",
        "security/ir.model.access.csv",
        "data/helpdesk_stage_data.xml",
        "data/helpdesk_sequence.xml",
        "views/helpdesk_tag_views.xml",
        "views/helpdesk_stage_views.xml",
        "views/helpdesk_team_views.xml",
        "views/helpdesk_ticket_views.xml",
        "views/helpdesk_menus.xml",
    ],
    "demo": ["demo/helpdesk_demo.xml"],
    "images": ["static/description/screenshot_01_kanban-pipeline.png"],
    "installable": True,
    "application": True,
}
