{
    "name": "Abonnements — Oski",
    "version": "19.0.1.0.0",
    "category": "Sales/Subscriptions",
    "summary": "Gérez vos abonnements et facturez automatiquement chaque client au bon rythme — sans Enterprise.",
    "author": "OdooSkills",
    "website": "https://apps.odooskills.com",
    "support": "apps@odooskills.com",
    "license": "LGPL-3",
    "depends": ["sale", "account"],
    "data": [
        "security/subscription_security.xml",
        "security/ir.model.access.csv",
        "data/ir_sequence_data.xml",
        "data/ir_cron_data.xml",
        "data/subscription_plan_data.xml",
        "views/sale_subscription_views.xml",
        "views/sale_subscription_plan_views.xml",
        "views/subscription_menus.xml",
    ],
    "demo": ["demo/subscription_demo.xml"],
    "images": ["static/description/screenshot_01_liste_abonnements.png"],
    "installable": True,
    "application": True,
}
